N/N/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('taskapp.urls')),
    path('task/', include('task.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

N/task/urls.py
from django.urls import path
from . import views

app_name = 'task'

urlpatterns = [
    path('', views.taskTop.as_view(), name='task_top'),
    path('task_top_out/', views.taskTop_out.as_view(), name='task_top_out'),
    path('build_project/', views.BuildProject.as_view(), name='build_project'),
    path('ProjectPage/', views.ProjectPage.as_view(), name='our_project'),
    path('FollowPage/', views.FollowPage.as_view(), name='follow'),
    path('AlreadyPage/', views.AlreadyPage.as_view(), name='already'),
    path('ProjectPage/<int:pk>/detail', views.ProjectDetail.as_view(), name='our_project_detail'),
    path('ProjectPage/<int:pk>/update', views.ProjectUpdate.as_view(), name='our_project_update'),
    path('ProjectPage/<int:pk>/task_update', views.TaskUpdate.as_view(), name='task_update'),
    path('ProjectPage/<int:pk>/delete', views.ProjectDelete.as_view(), name='our_project_delete'),
    path('ProjectPage/<int:pk>/update_member', views.UpdateProjectMember.as_view(), name='update_member'),
    path('ProjectPage/<int:pk>/delete_member', views.ProjectDeleteMember.as_view(), name='our_project_delete_member'),
    path('ProjectPage/<int:pk>/AATask', views.AddTaskForAjax.ajax_response, name='add_task'),
    path('ajax/getProjectTaskInfo',views.getProjectTaskInfoAjax.ajax_response, name='getPJTask')
]

N/task/forms.py
from django import forms
from .models import Already, Project, ProjectToUsers, Subject,Follow
from taskapp.forms import User

""" プロジェクト作成 """
class ProjectCreate(forms.ModelForm):

    class Meta:
        model = Project
        fields = (
            'name', 'leader',
            'start_date', 'end_date',
            'details','url',
        )
    

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
        self.fields['leader'].widget.attrs['hidden'] = 'true'
        self.fields['start_date'].widget.input_type = "date"
        self.fields['end_date'].widget.input_type="date"
        self.fields['url'].widget.input_type="string"

""" プロジェクト更新 """
class ProjectUpdate(forms.ModelForm):

    class Meta:
        model = Project
        fields = (
            'name',
            'start_date', 'end_date',
            'details','url',
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
        self.fields['start_date'].widget.input_type = "date"
        self.fields['end_date'].widget.input_type="date"
        self.fields['url'].widget.input_type="string"

""" 提出済み更新 """
class TaskUpdate(forms.ModelForm):

    class Meta:
        model = Project
        fields = (
            'is_already',
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
        self.fields['is_already'].widget.attrs['hidden'] = 'true'
    

class Subject_all(forms.ModelForm):
    class Meta:
        model = Subject
        fields = (
            'subject_name','subject_cd'
        )
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
        self.fields['subject_name'].widget.input_type="string"

class Follows(forms.ModelForm):
    class Meta:
        model = Follow
        fields = (
            'subject_name','subject_cd'
        )
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
        self.fields['subject_name'].widget.input_type="string"

class Alreadys(forms.ModelForm):
    class Meta:
        model = Already
        fields = (
            'project_cd','name'
        )
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
        self.fields['name'].widget.input_type="string"

""" プロジェクト削除 """
class ProjectDelete(forms.ModelForm):

    class Meta:
        model = Project
        fields = (
            'is_delete',
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['is_delete'].widget.attrs['hidden'] = 'true'

""" メンバー追加 """
class AddProjectMember(forms.ModelForm):

    class Meta:
        model = ProjectToUsers
        fields = (
            'project_cd',
            'user_cd'
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        where = []

        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
        self.fields['project_cd'].widget.attrs['hidden'] = 'true'

        leader = Project.objects.filter(project_cd=self.initial["project_cd"])
        in_member = ProjectToUsers.objects.filter(project_cd=self.initial["project_cd"])
        staff = User.objects.filter(is_staff=1)
        non_active = User.objects.filter(is_active=0)

        where.append(leader[0].leader_id)
        for in_men in in_member:
            where.append(in_men.user_cd_id) 

        for s in staff:
            where.append(s.pk)

        for non in non_active:
            where.append(non.pk)
            user = self.request.user

        result = User.objects.exclude()

        self.fields['user_cd'].queryset = result

N/task/views.py
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models.query import QuerySet
from django.views import generic
from django.contrib.sites.shortcuts import get_current_site
from django.shortcuts import redirect, render, resolve_url
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.db import models
from .models import ProjectToUsers, Project
from .forms import ProjectCreate, Subject_all
from .forms import ProjectUpdate
from .forms import ProjectDelete
from .forms import AddProjectMember
from .forms import Follows
from .forms import Alreadys
from .forms import TaskUpdate
from django.http.response import JsonResponse
from django.core import serializers
from .models import ProjectToUsers, Project, ProjectToTask, Task,Subject,Follow,Already
from django.views.decorators.csrf import csrf_exempt 
import datetime
import cgi # CGIモジュールのインポート
import cgitb
import sys
from taskapp.models import Schedule
import logging
import sys



User = get_user_model()


""" トップページ """
class taskTop(LoginRequiredMixin, generic.TemplateView):
    template_name = 'task/task_top.html'
    redirect_field_name = 'redirect_to'

    def get_context_data(self, **kwargs):
        user = self.request.user
        context = super().get_context_data(**kwargs)

        project_user = ProjectToUsers.objects.filter(user_cd=user.pk)
        leader = Project.objects.filter(leader=user.pk, is_delete=0)
        now_data = datetime.date.today()
        near = datetime.date.today() + datetime.timedelta(days=4)
        context["near"] = near
        context["td_data"] = now_data



        if len(project_user) > 0:
            context['member'] = []
            for person in project_user:
                member = Project.objects.filter(project_cd=person.project_cd.pk, is_delete=0)
                context['member'].extend(member)
        else:
            context['member'] = None

        context['leader'] = leader if len(leader) > 0 else None

        return context

""" トップページ期限切れ """
class taskTop_out(LoginRequiredMixin, generic.TemplateView):
    template_name = 'task/task_top_out.html'
    redirect_field_name = 'redirect_to'

    def get_context_data(self, **kwargs):
        user = self.request.user
        context = super().get_context_data(**kwargs)

        project_user = ProjectToUsers.objects.filter(user_cd=user.pk)
        leader = Project.objects.filter(leader=user.pk, is_delete=0)
        now_data = datetime.date.today()
        near = datetime.date.today() + datetime.timedelta(days=4)
        context["near"] = near
        context["td_data"] = now_data



        if len(project_user) > 0:
            context['member'] = []
            for person in project_user:
                member = Project.objects.filter(project_cd=person.project_cd.pk, is_delete=0)
                context['member'].extend(member)
        else:
            context['member'] = None

        context['leader'] = leader if len(leader) > 0 else None

        return context

""" プロジェクト作成 """
class BuildProject(LoginRequiredMixin, generic.CreateView):
    model = Project
    form_class = ProjectCreate
    success_url ='/task/'
    template_name = 'task/build_project.html'

    def get_initial(self): 
        leader = self.request.user.pk
        return {'leader': leader,}

    def form_valid(self, form):
        end_date = form.cleaned_data.get('end_date')
        name = form.cleaned_data.get('name')           
        obj= Schedule(date= end_date, summary= name)
        obj.save()
        return super().form_valid(form)

""" プロジェクト限定 """
class ProjectUserOnlyMixin(UserPassesTestMixin):
    raise_exception = True

    def test_func(self):
        is_return = True

        user = self.request.user

        l_result = Project.objects.filter(leader=user.pk, project_cd=self.kwargs["pk"])
        m_result = ProjectToUsers.objects.filter(project_cd=self.kwargs["pk"], user_cd=self.request.user.pk)
        p_result = Project.objects.filter(project_cd=self.kwargs["pk"], is_delete=0)
        if len(l_result) == 0 and len(m_result) == 0:
            is_return = False

        if len(p_result) == 0:
            is_return = False

        return is_return

""" プロジェクトページ """
class ProjectPage(LoginRequiredMixin, generic.TemplateView):
    model = Subject,Follow
    template_name = 'task/our_project.html'
    form_class = Subject_all
    success_url ='task/follow.html'

    def get_context_data(self, **kwargs):
        user = self.request.user
        context = super().get_context_data(**kwargs)
        
        subject = Subject.objects.all()
        
        context['subject'] = subject
        
        return context

    def post(self, request, *args, **kwargs):
        check = request.POST.getlist('subjects')
        for sub in check:
            query = Subject.objects.filter(subject_cd=sub)  
            obj = Follow(subject_cd=query[0].subject_cd,subject_name=query[0].subject_name)
            obj.save()
        return redirect("/")

""" フォロー科目ページ """
class FollowPage(LoginRequiredMixin, generic.TemplateView):
    model = Follow
    template_name = 'task/follow.html'
    form_class = Follows
    

    def get_context_data(self, **kwargs):
        user = self.request.user
        context = super().get_context_data(**kwargs)
        
        follow = Follow.objects.all()
        
        context['follow'] = follow
        
        return context

""" 提出済み課題ページ """
class AlreadyPage(LoginRequiredMixin, generic.TemplateView):
    
    template_name = 'task/already.html'
    form_class = Alreadys
    

    def get_context_data(self, **kwargs):
        user = self.request.user
        context = super().get_context_data(**kwargs)

        project_user = ProjectToUsers.objects.filter(user_cd=user.pk)
        leader = Project.objects.filter(leader=user.pk, is_delete=0)
        now_data = datetime.date.today()
        context["td_data"] = now_data



        if len(project_user) > 0:
            context['member'] = []
            for person in project_user:
                member = Project.objects.filter(project_cd=person.project_cd.pk, is_delete=0)
                context['member'].extend(member)
        else:
            context['member'] = None

        context['leader'] = leader if len(leader) > 0 else None

        return context

        

""" プロジェクトリーダ限定 """
class ProjectLeaderOnlyMixin(UserPassesTestMixin):
    raise_exception = True

    def test_func(self):
        is_return = True

        user = self.request.user

        l_result = Project.objects.filter(leader=user.pk, project_cd=self.kwargs["pk"])
        p_result = Project.objects.filter(project_cd=self.kwargs["pk"], is_delete=0)

        if len(l_result) == 0:
            is_return = False

        if len(p_result) == 0:
            is_return = False

        return is_return


""" プロジェクト情報 """
class ProjectDetail(ProjectUserOnlyMixin, generic.DetailView):
    model = Project
    template_name = 'task/project_detail.html'
    

    def get_context_data(self, **kwargs):
        user = self.request.user
        context = super().get_context_data(**kwargs)

        p_user = ProjectToUsers.objects.filter(project_cd=self.kwargs["pk"])
        project = Project.objects.filter(project_cd=self.kwargs["pk"], is_delete=0)

        context['member'] = p_user if len(p_user) > 0 else None

        context['project'] = project if len(project) > 0 else None

        return context


""" プロジェクト更新ページ """
class ProjectUpdate(ProjectUserOnlyMixin, generic.UpdateView):
    model = Project
    template_name = 'task/project_update.html'
    form_class = ProjectUpdate


    def get_success_url(self):
        return resolve_url('task:our_project_detail', pk=self.kwargs["pk"])

""" 提出済み更新ページ """
class TaskUpdate(ProjectUserOnlyMixin, generic.UpdateView):
    model = Project
    template_name = 'task/task_update.html'
    form_class = TaskUpdate

    def get_context_data(self, **kwargs):
        user = self.request.user
        context = super().get_context_data(**kwargs)
        p_user = ProjectToUsers.objects.filter(project_cd=self.kwargs["pk"])
        project = Project.objects.filter(project_cd=self.kwargs["pk"], is_delete=0)
        

        if len(p_user) > 0:
            context['member'] = []
            for person in p_user:
                member = User.objects.filter(pk=person.user_cd.pk)
                context['member'].extend(member)
        else:
            context['member'] = None

        context['project'] = project if len(project) > 0 else None

        return context

    def get_initial(self): 

        return {'is_already': True,}

    def get_success_url(self):
        project = Project.objects.filter(project_cd=self.kwargs["pk"], is_delete=0)
        Schedule.objects.filter(summary=project[0].name).delete()
        return resolve_url('task:task_top')


""" プロジェクト削除ページ """
class ProjectDelete(ProjectLeaderOnlyMixin, generic.UpdateView):
    model = Project
    template_name = 'task/project_delete.html'
    form_class = ProjectDelete

    def get_context_data(self, **kwargs):
        user = self.request.user
        context = super().get_context_data(**kwargs)
        p_user = ProjectToUsers.objects.filter(project_cd=self.kwargs["pk"])
        project = Project.objects.filter(project_cd=self.kwargs["pk"], is_delete=0)
        Schedule.objects.filter(summary=project[0].name).delete()
        if len(p_user) > 0:
            context['member'] = []
            for person in p_user:
                member = User.objects.filter(pk=person.user_cd.pk)
                context['member'].extend(member)
        else:
            context['member'] = None

        context['project'] = project if len(project) > 0 else None

        return context

    def get_initial(self): 
        return {'is_delete': True,}

    def get_success_url(self):
        return resolve_url('task:already')

""" プロジェクトメンバー追加 """

N/task/templates/task/already.html
{% extends "base.html" %}
{% block title %} TaskMan {% endblock %}
{% block mainT %} 提出済み課題 {% endblock %}
{% block body %}
<div style="padding:20px 200px 0px 200px;"></div>
<center>
    <h2 style="margin-bottom: 20px;">
        <font color="#589BFE">提出済み課題</font>
    </h2>
    {% if leader != None %}
    {% for lead in leader %}
    {% if lead.is_already == 1 %}
    <div>
    <a class="btn" href="{% url 'task:our_project_detail' lead.pk %}" style="margin-bottom: 20px; background-color: #F4F8FA; border-color:#C3DDEB; text-align:center; width: 800px;">
        <span>{{lead.leader}}</span>
        【{{lead.name}}】

        {% if lead.now_date != None %}
        <span>今の日付 : {{lead.now_date}}</span>
        {% endif %}

        {% if lead.end_date != None %}
        <span>期限 : {{lead.end_date}}</span>
        {% endif %}
    </a>
    </div>
    {% endif %}
    {% endfor %}
    {% else %}
    <h2 style="margin-top: 300px;">
        <font color="#589BFE">課題がありません</font>
    </h2>
    {% endif %}
</center>






{% endblock %}

N/task/templates/task/build_project.html
{% extends "base.html" %}
{% block title %} TaskApp　{% endblock %}
{% block mainT %} 課題作成 {% endblock %}
{% block mainL %}User : {{ user.get_username }}{% endblock %}
{% block auth %}{% endblock %}
{% block body %}
<div style="padding:20px 200px 0px 200px;">
    <form action="" method="POST">
        {{ form.non_field_errors }}
        {% for field in form %}
        <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
            {{ field }}
            <span style="color:red">{{ field.errors }}</span>
        </div>
        {% endfor %}
        {% csrf_token %}
        <button type="submit" class="btn btn-primary btn-lg">登録</button>
        <a href="/task" class="btn btn-primary btn-lg">戻る</a>
    </form>
</div>
{% endblock %}

N/task/templates/task/follow.html
{% extends "base.html" %}
{% block title %} TaskMan {% endblock %}
{% block mainT %} 科目一覧 {% endblock %}
{% block body %}
<div style="padding:20px 200px 0px 200px;">
    <center>
        <h2 style="margin-bottom: 20px;">
            <font color="#589BFE">フォロー済み科目</font>
        </h2>
        {% if follow != None %}
        <form action="" method="POST">
            {% csrf_token %}
            {{ follow.non_field_errors }}
            {% for field in follow %}
            <div class="btn" style="margin-bottom: 20px; background-color: #F4F8FA; border-color:#C3DDEB; text-align:center; width: 800px;">
                {{ field.subject_name }}　　　　／　　　　{{ field.subject_koushi }}
            </div>
            {% endfor %}
        </form>
        {% else %}
        <h4>科目がありません</h4>
        {% endif %}
    </center>
</div>
{% endblock %}

N/task/templates/task/kadaicheck.html
{% extends "base.html" %}
{% block title %} TaskMan {% endblock %}
{% block mainT %} パスワード変更 {% endblock %}
{% block body %}
<div style="text-align: center; padding-top: 50px;">
    <h2>課題を提出しましたか？</h2>
    <a href="/task/" class="btn btn-primary" style="width: 140px; margin-right:10px;">課題一覧に戻る</a>
    <form action="" method="POST">
        <button type="submit" class="btn btn-primary" style="width: 140px; margin-right:10px;" value="">提出済みに登録</button>
        {% csrf_token %}
    </form>
</div>
{% endblock %}

N/task/templates/task/kamokuadd.html
{% extends "base.html" %}
{% block title %} TaskMan {% endblock %}
{% block mainT %}  {{ project.0.name }} {% endblock %}
{% block body %}

<<<<<<< HEAD
<nav class=" navbar-dark bg-dark flex-md-nowrap p-0 header">
    <a class="navbar-brand col-md-1 mr-0" href="/task/">戻る</a>
    <a  class="navbar-brand col-md-2 mr-0" href="{% url 'task:our_project_detail' project.0.pk %}"> プロジェクト詳細 </a>
    <a class="navbar-brand col-md-2 mr-0" href="{% url 'task:add_task' project.0.pk %}">タスク追加</a>
    <div class="btn-group">
        <div class="btn dropdown-toggle naviDrop" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            メンバー
        </div>
            <div class="dropdown-menu dropdown-menu-right" >
                <a class="dropdown-item" href="#"> {{ project.0.leader }} </a>
                {% if member != None %}
                    <div class="dropdown-divider"></div>
                    {% for person in member %}
                    <a class="dropdown-item" href="#"> {{ person }} </a>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>
</nav>
<script type="text/javascript">
    $(function(){
      var d = sessionStorage.getItem('key');
      $("#result").text(d);
    })
    </script>
<!--切り替え用ボタン-->
<div class="text-center">
    <a type="button" class=" btn text-dark w-25 mr-3 check_button" style="background-color: rgb(195,221,235);" href="{% url 'task:our_project' project.0.pk %}">フォロー未</a>
    <img src="/static/img/スラッシュ.png" style="height: 25px; width: 25px;">　
    <a type="button" class="btn text-dark w-25 check_button" style="background-color: rgb(244,248,250);" href="{% url 'task:our_project_kamokuadd' project.0.pk %}">フォロー済</a>
</div>
=======
<h2 class="kensakuTitle">検索結果</h2>
>>>>>>> ba19a6a84e86b5b44acd4e59c41b3604fa96728d

<div id="taskList">
<<<<<<< HEAD
    {% if task == None %}
    <div class="cp_ipcheck">
        <ul>
            <li><p id="result"></p></li>
            <li>{{ project.0.name }}　　　　　　　　　　<img src="/static/img/スラッシュ.png" style="height: 25px; width: 25px;">　　　　　　　　　　{{ project.0.leader }}<input type="checkbox" class="option-input02 checkbox" ></li>
            <li>{{ project.0.name }}　　　　　　　　　　<img src="/static/img/スラッシュ.png" style="height: 25px; width: 25px;">　　　　　　　　　　{{ project.0.leader }}<input type="checkbox" class="option-input02 checkbox" ></li>
        </ul>
    </div>
    {% else %}
=======
>>>>>>> ba19a6a84e86b5b44acd4e59c41b3604fa96728d
    <div class="cp_ipcheck">
        <ul>
            <li>{{ project.0.name }}　　　　　　　　　　<img src="/static/img/スラッシュ.png" style="height: 25px; width: 25px;">　　　　　　　　　　{{ project.0.leader }}<input type="checkbox" class="option-input02 checkbox" id="checkbox" name="checkbox" value="フォロー"></li>
        </ul>
    </div>
<<<<<<< HEAD
    {% endif %}
</div>
{% endif %}

=======
</div>
>>>>>>> ba19a6a84e86b5b44acd4e59c41b3604fa96728d
{% endblock %}

N/task/templates/task/our_project.html
{% extends "base.html" %}
{% block title %} TaskMan {% endblock %}
{% block mainT %} 科目追加 {% endblock %}
{% block body %}
<div style="padding:20px 200px 0px 200px;" class="form-group">
    <center>
        <h2 style="margin-bottom: 20px;">
            <font color="#589BFE">検索結果</font>
        </h2>
        {% if subject != None %}
        <form action="" method="POST">
            {% csrf_token %}
            {{ subject.non_field_errors }}
            {% for field in subject %}
            <div class="btn"
                style="margin-bottom: 20px; background-color: #F4F8FA; border-color:#C3DDEB; text-align:center; width: 800px; top:50px;">
                <div style="text-align: center;">
                    {{ field.subject_name }}　　　　／　　　　{{ field.subject_koushi }}<label class="ECM_CheckboxInput"
                        style="float:right"><input class="ECM_CheckboxInput-Input" type="checkbox" name="subjects"
                            value="{{ field.subject_cd }}" style="margin-bottom: 20px;">
                        <div class="ECM_CheckboxInput-DummyInput"></div>
                    </label>
                </div>
            </div>
            {% endfor %}
            <br>
            <button type="submit">フォロー</button>
            <button><a href="/">戻る</a></button>
        </form>
        {% else %}
        <h4>科目がありません</h4>
        {% endif %}
    </center>
</div>

{% endblock %}

N/task/templates/task/our_project_after.html
{% extends "base.html" %}
{% block title %} TaskMan {% endblock %}
{% block mainT %}  {{ project.0.name }} {% endblock %}
{% block body %}

<nav class=" navbar-dark bg-dark flex-md-nowrap p-0 header">
    <a class="navbar-brand col-md-1 mr-0" href="/task/">戻る</a>
    <a  class="navbar-brand col-md-2 mr-0" href="{% url 'task:our_project_detail' project.0.pk %}"> プロジェクト詳細 </a>
    <a class="navbar-brand col-md-2 mr-0" href="{% url 'task:add_task' project.0.pk %}">タスク追加</a>
    <div class="btn-group">
        <div class="btn dropdown-toggle naviDrop" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            メンバー
        </div>
            <div class="dropdown-menu dropdown-menu-right" >
                <a class="dropdown-item" href="#"> {{ project.0.leader }} </a>
                {% if member != None %}
                    <div class="dropdown-divider"></div>
                    {% for person in member %}
                    <a class="dropdown-item" href="#"> {{ person }} </a>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>
</nav>

<!--切り替え用ボタン-->
<div class="text-center">
    <button onclick="location.href='our_project.html" type="button" class=" btn text-dark w-25 mr-3" style="background-color: rgb(195,221,235);">期限内未提出</button>
    <img src="/static/img/スラッシュ.png" style="height: 25px; width: 25px;">　
    <button onclick="location.href='our_project_after.html" type="button" class="btn text-dark w-25" style="background-color: rgb(244,248,250)">期限切れ未提出</button>
</div>


{% if task == None %}
<div id="taskList">
    {% if task == None %}
        <ul>
            <li>タスクがありません</li>   
            <li>タスクがありません</li>
            <li>タスクがありません</li>     
            <li>タスクがありません</li>
        </ul>
    {% else %}
        <ul id="taskAccordion">
            {% for content in task %}

                <li class="selectTask task{{content.priolity}}" value="{{content.task_cd}}"> {{content.task_name}} </li> 
            {% endfor %}
        </ul>
    {% endif %}

</div>
{% endif %}
{% endblock %}

N/task/templates/task/project_detail.html
{% extends "base.html" %}
{% block title %} TaskMan {% endblock %}
{% block mainT %} 課題詳細情報 {% endblock %}
{% block body %}
<div style="margin:20px;">
    <div class="simple-border1">
        <div class="box2" style="border-width: 0px 0px 7px 0px;  border-color:#589BFE">
            <div style="text-align:center;">
                <span style="font-size:230%;">{{ project.0.name }}(科目名)</span>
                <span style="font-size: 230%; margin-left: 18%;">講師名:{{ project.0.leader }}</span>
            </div>
        </div>
    </div>
    <table class="table">

        <div class="kadai-detail" style="margin-top: 50px; text-align: center; font-size: 150%;">
            <span>
                <div class="box1">{{ project.0.details }}</div>
            </span>
            <div style="text-align:match-parent;">
                <span>
                    <p style="margin-top: 20px;"><img src="/static/img/印.png" style="height: 25px; width: 25px;"><a
                            href="{{ project.0.url }}" target="_blank">{{ project.0.url }}</a></p>
                </span>
            </div>
            <div style="text-align:match-parent; margin-top:50px;">
                <span>
                    <span>提出期限:</span>
                    <span style="color:red;">{{ project.0.end_date }}</span>
                </span>
            </div>
            <div style="text-align:right; margin-right: 150px">
                <img src="/static/img/チャット.png">
            </div>
        </div>
    </table>
    <hr>
    <center>
        <a href="{% url 'task:task_top' %}" class="btn btn-primary">戻る</a>
        <a href="{% url 'task:our_project_update' project.0.pk %}" class="btn btn-primary ">変更</a>
        <a href="{% url 'task:our_project_delete' project.0.pk %}" class="delete-btn btn btn-primary" style="border-color: red;">削除</a>
        <a href="{% url 'task:task_update' project.0.pk %}" class="btn btn-primary ">提出済みに変更</a>
    </center>
</div>
{% endblock %}

N/task/templates/task/project_update.html
{% extends "base.html" %}
{% block title %} TaskMan {% endblock %}
{% block mainT %} 更新 {% endblock %}
{% block body %}
<div style="margin:20px">
    <form action="" method="POST">
        {{ form.non_field_errors }}
        <table class="table">
            <tbody>
                {% for field in form %}
                    <tr>
                        <th><label for="{{ field.id_for_label }}">{{ field.label }}</label></th>
                        <td>{{ field }} <span style="color:red">{{ field.errors }}</span></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% csrf_token %}
        <a href="{% url 'task:our_project_detail' project.pk %}" class="btn btn-primary">戻る</a>
        <button type="submit" class="btn btn-success">更新</button>
    </form>
</div>
{% endblock %}