N/N/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('taskapp.urls')),
    path('task/', include('task.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

N/task/urls.py
from django.urls import path
from . import views

app_name = 'task'

urlpatterns = [
    path('', views.taskTop.as_view(), name='task_top'),
    path('task_top_out/', views.taskTop_out.as_view(), name='task_top_out'),
    path('build_project/', views.BuildProject.as_view(), name='build_project'),
    path('ProjectPage/', views.ProjectPage.as_view(), name='our_project'),
    path('FollowPage/', views.FollowPage.as_view(), name='follow'),
    path('AlreadyPage/', views.AlreadyPage.as_view(), name='already'),
    path('ProjectPage/<int:pk>/detail', views.ProjectDetail.as_view(), name='our_project_detail'),
    path('ProjectPage/<int:pk>/update', views.ProjectUpdate.as_view(), name='our_project_update'),
    path('ProjectPage/<int:pk>/task_update', views.TaskUpdate.as_view(), name='task_update'),
    path('ProjectPage/<int:pk>/delete', views.ProjectDelete.as_view(), name='our_project_delete'),
    path('ProjectPage/<int:pk>/update_member', views.UpdateProjectMember.as_view(), name='update_member'),
    path('ProjectPage/<int:pk>/delete_member', views.ProjectDeleteMember.as_view(), name='our_project_delete_member'),
    path('ProjectPage/<int:pk>/AATask', views.AddTaskForAjax.ajax_response, name='add_task'),
    path('ajax/getProjectTaskInfo',views.getProjectTaskInfoAjax.ajax_response, name='getPJTask')
]

N/taskapp/urls.py
from django.urls import path
from . import views

app_name = 'taskapp'

urlpatterns = [
    path('',views.MonthWithScheduleCalendar.as_view(), name='month_with_schedule'),
    path( 'month_with_schedule/', views.MonthWithScheduleCalendar.as_view(), name='month_with_schedule'),
    path('month_with_schedule/<int:year>/<int:month>/',views.MonthWithScheduleCalendar.as_view(), name='month_with_schedule'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('registration/', views.Registration.as_view(), name='registration'),
    path('registration/complete', views.RegistrationComp.as_view(), name='registration_complete'),
    path('profile/<int:pk>/', views.Profile.as_view(), name='profile'),
    path('profile/<int:pk>/update/', views.ProfileUpdate.as_view(), name='profile_update'),
    path('profile/<int:pk>/password', views.PasswordChange.as_view(), name='password'),
    path('profile/<int:pk>/password/complete', views.PasswordChangeComplete.as_view(), name='password_complete'),
]

N/taskapp/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser


class User(AbstractUser, models.Model):
    icon = models.ImageField(
        upload_to='img/',
        verbose_name='アイコン',
        blank=True,
    )

class Schedule(models.Model):
    """スケジュール"""
    summary = models.CharField('概要', max_length=50)
    description = models.TextField('詳細な説明', blank=True)
    start_time = models.TimeField('開始時間', default=datetime.time(7, 0, 0))
    end_time = models.TimeField('終了時間', default=datetime.time(7, 0, 0))
    date = models.DateField('日付')
    created_at = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        return self.summary

N/taskapp/forms.py
from django.contrib.auth.forms import (
    AuthenticationForm
)
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

User = get_user_model()

"""ログインフォーム"""
class LoginForm(AuthenticationForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label


"""アカウント登録フォーム"""
class RegistrationForm(UserCreationForm):

    class Meta:
        model = User
        fields = (
            'id',
            'username', 'email',
            'password1', 'password2',
            'last_name', 'first_name',
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

""" アカウント更新フォーム """
class AccountsUpdateForm(forms.ModelForm):

    class Meta:
        model = User
        fields = (
            'icon',
            'username', 'email',
            'last_name', 'first_name',
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

N/taskapp/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView
from django.views import generic
from django.contrib.auth.decorators import login_required
from .forms import LoginForm
from django.conf import settings
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth import get_user_model
from .forms import RegistrationForm
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import redirect, resolve_url
from .forms import LoginForm, RegistrationForm, AccountsUpdateForm
from task.models import ProjectToUsers, Project
from django.views import generic
from . import mixins
from .models import Schedule


User = get_user_model()


"""ログインページ"""
class Login(LoginView):
    template_name = 'login.html'
    form_class = LoginForm


""" トップページ """
class Top(LoginRequiredMixin, generic.TemplateView):
    template_name = 'top.html'
    redirect_field_name = 'redirect_to'

"""ログアウトページ"""
class Logout(LoginRequiredMixin, LogoutView):
    template_name = 'logout.html'

    """アカウント登録ページ"""
class Registration(generic.CreateView):
    model = User
    template_name = 'registration.html'
    form_class = RegistrationForm
    success_url ='/registration/complete'


"""アカウント登録完了"""
class RegistrationComp(generic.TemplateView):
    template_name = 'registration_complete.html'

""" ユーザ限定クラス """
class UserOnlyMixin(UserPassesTestMixin):
    raise_exception = True

    def test_func(self):
        user = self.request.user
        return user.pk == self.kwargs['pk'] or user.is_superuser


""" ユーザ情報表示ページ """
class Profile(UserOnlyMixin, generic.DetailView):
    model = User
    template_name = 'profile.html'


""" ユーザ情報更新ページ """
class ProfileUpdate(UserOnlyMixin, generic.UpdateView):
    model = User
    form_class = AccountsUpdateForm
    template_name = 'profile_update.html'

    def get_success_url(self):
        return resolve_url('taskapp:profile', pk=self.kwargs['pk'])

""" パスワード変更ページ """
class PasswordChange(UserOnlyMixin, PasswordChangeView):
    model = User
    template_name = 'password_change.html'

    def get_success_url(self):
        return resolve_url('taskapp:password_complete', pk=self.kwargs['pk'])

""" パスワード変更完了 """
class PasswordChangeComplete(UserOnlyMixin, PasswordChangeDoneView):
    template_name = 'password_change_complete.html'

class MonthWithScheduleCalendar(mixins.MonthWithScheduleMixin, generic.TemplateView):
    """スケジュール付きの月間カレンダーを表示するビュー"""
    model = Schedule
    template_name = 'top.html'
    date_field = 'date'

    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        calendar_context = self.get_month_calendar()
        context.update(calendar_context)
        
        return context

N/taskapp/templates/base.html
<!DOCTYPE html>
<html lang='ja'>

<head>
    {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/デフォルト.png' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
        integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'css/modal.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/adjustment.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/navibar.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/slider.css' %}" rel="stylesheet" type="text/css">
    <script type="text/javascript" src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'js/ajax.js' %}"></script>
    <script src="{% static 'js/modal.js' %}"></script>
    <script src="{% static 'js/masta.js' %}"></script>
    <script src="{% static 'js/navibar.js' %}"></script>

</head>

<body>
    <nav class="navbar navbar-dark sticky-top flex-md-nowrap p-0" style="background-color: rgb(244,248,250);">
        <a class="navbar-brand col-sm-3 col-md-2 mr-0 barbtn text-dark" style="background-color: rgb(195,221,235);"
            href="">{{ user.last_name }}　{{ user.first_name }}　(R4)</a>
        <div style="margin-right: 6%;">{% block mainT %}{% endblock %}</div>
        <div class="btn-group">
            <div class="btn dropdown-toggle naviDrop" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {% if user.is_authenticated %}
                User : {{ user.get_username }}
                {% if user.icon.url != "" %}
                <img src="{{ user.icon.url }}" style="height: 20px; width: 20px;">
                {% else %}
                <img src="/static/img/デフォルト.png" style="height: 20px; width: 20px;">
                {% endif%}
                {% else %}
                User
                {% endif %}
            </div>
            {% if user.is_authenticated %}
            <div class="dropdown-menu dropdown-menu-right">
                <a class="dropdown-item" href="{% url 'taskapp:profile' user.pk %}">ユーザ情報</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="/logout/">ログアウト</a>
            </div>
            {% endif %}
        </div>
    </nav>

    <div class="drawr col-sm-3 col-md-2">
        <div class="barmenu"><a href="/"><img src="/static/img/ホーム.png" style="height: 25px; width: 25px;">　ホーム</a>
        </div>
        <div class="barmenu"><a href="{% url 'task:task_top' %}"><img src="/static/img/課題.png"
                    style="height: 25px; width: 25px;">　課題一覧</a></div>
        <div class="barmenu"><a href="{% url 'task:follow' %}"><img src="/static/img/課題２.png"
                    style="height: 25px; width: 25px;">　科目一覧</a></div>
        <div class="barmenu"><a href="{% url 'task:our_project' %}"><img src="/static/img/その他.png"
                    style="height: 25px; width: 25px;">　科目追加</a></div>
        <div class="barmenu"><a href="{% url 'task:already' %}"><img src="/static/img/その他.png"
                    style="height: 25px; width: 25px;">　提出済み課題</a></div>
        <div class="barmenu"><a href="#"><img src="/static/img/通知.png" style="height: 25px; width: 25px;">　通知</a></div>
        <div class="barmenu"><a href=""><img src="/static/img/設定.png" style="height: 25px; width: 25px;">　設定</a></div>
    </div>

    {% block body %}{% endblock %}

</body>

<body>

    <div class="container" mt-3>
        {% block content %}{% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.6.0.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
        integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
        crossorigin="anonymous"></script>
    {% block extrajs %}{% endblock %}
</body>

</html>

N/taskapp/templates/login.html
{% extends "base.html" %}
{% block body %}

<body style="background-color:#F4F8FA;">
    <div style='padding-top: 50px;'>
        <div style="text-align:left; margin-left: 150px; margin-bottom: 50px;">
            <img src="/static/img/タイトル.png" width="30%" height="50%">
        </div>

        <form action="" method="POST">
            <div class="col-md-6 offset-md-3">


                <div class="form-group">
                    {{ form.non_field_errors }}
                    {% for field in form %}
                    {{ field }}
                    {{ field.errors }}
                    <p style="margin-top:40px"></p>
                    {% endfor %}
                </div>
                <div class="authElement">
                    <a><button type="submit" class="btn"
                            style="background-color: #589BFE; text-align:center; width: 150px">ログイン</button>
                        <input type="hidden" name="next" value="{{ next }}" />
                        {% csrf_token %}
                    </a>
                    <p></p>
                    <a class="btn" href="/registration/"
                        style="background-color: #C3DDEB; text-align:center; width: 150px;">新規登録</a>
                </div>
            </div>
        </form>
    </div>

</body>
{% endblock %}

N/taskapp/templates/logout.html
{% extends "base.html" %}
{% block title %} TaskApp {% endblock %}
{% block mainT %} ログアウト {% endblock %}
{% block mainL %}UserID : {{ user.get_username }}{% endblock %}
{% block auth %}{% endblock %}
{% block body %}
<div style="text-align: center; padding-top: 50px;">
    <h2>お疲れ様でした</h2>
    <a class="nav-link" href="../login/">ログイン</a>
</div>
{% endblock %}

N/taskapp/templates/password_change.html
{% extends "base.html" %}
{% block title %} TaskMan {% endblock %}
{% block mainT %} パスワード変更 {% endblock %}
{% block body %}
<div style="margin:100px">
    <form action="" method="POST">
        {{ form.non_field_errors }}
        {% for field in form %}
        <div class="form-group" style="text-align: center; margin-right: 15%;">
            <label class="col-6" for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
            {{ field }}
            <span style="color:red">{{ field.errors }}</span>
        </div>
        {% endfor %}
        {% csrf_token %}
        <div class="form-group" style="text-align: center;">
            <div class="authElement">
                <a href="{% url 'taskapp:profile' user.pk %}" class="btn btn-primary" style="margin-right: 15%;">戻る</a>
                <button type="submit" class="btn btn-success">変更</button>
            </div>
        </div>
    </form>

</div>
{% endblock %}

N/taskapp/templates/password_change_complete.html
{% extends "base.html" %}
{% block title %} TaskMan {% endblock %}
{% block mainT %} パスワード変更 {% endblock %}
{% block body %}
<div style="text-align: center; padding-top: 50px;">
    <h2>パスワードを変更しました</h2>
    <div class="authElement">
        <a href="{% url 'taskapp:profile' user.pk %}" class="btn btn-primary">ユーザ情報</a>
    </div>
</div>
{% endblock %}

N/taskapp/templates/profile.html
{% extends "base.html" %}
{% block title %} TaskMan {% endblock %}
{% block mainT %} 設定 {% endblock %}
{% block body %}
<div style="margin:20px">
    <div class="icon">
        {% if user.icon.url != "" %}
        <img src="{{ user.icon.url }}" style="height: 100px; width: 100px;">
        {% else %}
        <img src="/static/img/デフォルト.png" style="height: 50px; width: 50px;">
        {% endif%}
    </div>
    <table class="table">
        <tbody>
            <tr>
                <th>ユーザー名</th>
                <td>{{ user.username }}</td>
            </tr>
            <tr>
                <th>メールアドレス</th>
                <td>{{ user.email }}</td>
            </tr>
            <tr>
                <th>姓</th>
                <td>{{ user.last_name }}</td>
            </tr>
            <tr>
                <th>名</th>
                <td>{{ user.first_name }}</td>
            </tr>
        </tbody>
    </table>
    <a href="{% url 'taskapp:profile_update' user.pk %}" class="btn btn-primary ">変更</a>
    <a href="{% url 'taskapp:password' user.pk %}" class="btn btn-primary ">パスワード変更</a>
</div>
{% endblock %}

N/taskapp/templates/profile_update.html
{% extends "base.html" %}
{% block title %} TaskMan {% endblock %}
{% block mainT %} アカウント情報 更新 {% endblock %}
{% block body %}
<div style="margin:20px">
    <form action="" method="POST">
        {{ form.non_field_errors }}
        {% for field in form %}
        <div class="form-group" style="text-align: center;">
            <label class="col-6" for="{{ field.id_for_label }}" style="text-align: left;">{{ field.label_tag }}{{ field
                }}</label>
            <span style="color:red">{{ field.errors }}</span>
            {% endfor %}
            {% csrf_token %}
            <br>
            <button type="submit" class="btn btn-primary" style="text-align: right; margin-top:20px">保存</button>
        </div>
    </form>
</div>
{% endblock %}

N/taskapp/templates/registration.html
{% extends "base.html" %}
{% block title %} TaskApp　{% endblock %}
{% block mainT %} アカウント作成 {% endblock %}
{% block mainL %}User : {{ user.get_username }}{% endblock %}
{% block auth %}{% endblock %}
{% block body %}

<body style="background-color:#F4F8FA;">
    <div style='padding-top: 50px;'>
        <div style="text-align:left; margin-left: 150px; margin-bottom: 30px;">
            <img src="/static/img/新規登録.png" width="30%" height="50%">
        </div>
        <div style="padding:0px 200px 0px 200px;">
            <form action="" method="POST">
                {{ form.non_field_errors }}
                {% for field in form %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}">
                        <font color="#589BFE">{{ field.label_tag }}</font>
                    </label>
                    {{ field }}
                    <span style="color:red">{{ field.errors }}</span>
                </div>
                {% endfor %}
                {% csrf_token %}
                <div class="authElement">
                    <button type="submit" class="btn"
                        style="background-color: #589BFE; text-align:center; width: 150px">登録</button>
                </div>
            </form>
        </div>
</body>
{% endblock %}

N/taskapp/templates/registration_complete.html
{% extends "base.html" %}
{% block title %} TaskApp　{% endblock %}
{% block mainT %} アカウント作成 {% endblock %}
{% block mainL %}User : {{ user.get_username }}{% endblock %}
{% block auth %}{% endblock %}
{% block body %}
<div style="text-align: center; padding-top: 150px;">
    <h2>新規登録が完了しました</h2>
    <a class="nav-link" href="/login/" style="text-align: center; padding-top:50px;">ログイン</a>
</div>
{% endblock %}

N/taskapp/templates/top.html
{% extends "base.html" %}
{% block title %} TaskApp {% endblock %}
{% block mainT %} ホーム {% endblock %}
{% block mainL %}UserID : {{ user.get_username }}{% endblock %}
{% block auth %}<a class="nav-link" href="../logout/">ログアウト</a>{% endblock %}
{% block content %}
<style>
    table {
        table-layout: fixed;

    }

    td>div {
        height: 125px;

        white-space: nowrap;
    }
</style>
<a href="{% url 'taskapp:month_with_schedule' month_previous.year month_previous.month %}">＜</a>
{{ month_current | date:"Y年m月" }}
<a href="{% url 'taskapp:month_with_schedule' month_next.year month_next.month %}">＞</a>
<table class="table table-bordered">
    <thead>
        <tr>
            {% for w in week_names %}
            <th>
                <div class="text-center">{{ w }}</div>
            </th>
            {% endfor %}
        </tr>
    </thead>
    <tbody>
        {% for week_day_schedles in month_day_schedules %}
        <tr>
            {% for day, schedules in week_day_schedles.items %}
            {% if now == day %}
            <td class="table-success">
                {% else %}
            <td>
            {% endif %}

                <div>
                    {% if month_current.month != day.month %}
                    {{ day | date:"m/d" }}
                    {% else %}
                    {{ day.day }}
                    {% endif %}
                    <br>
                    {% for schedule in schedules %}
                    {% if day < near %} 
                    <a class="btn" href="{% url 'task:our_project_detail' schedule.pk%}"
                        style="position: relative; left:-13px; background-color: #FF6600; text-align:left; width: 160px;">
                        {{ schedule.summary }}</a>
                        {% else %}
                        <a class="btn" href="{% url 'task:our_project_detail' schedule.pk%}"
                            style="position: relative; left:-13px; background-color: #589BFE; text-align:left; width: 160px;">{{schedule.summary}}</a>
                        {% endif %}

                        <br>
                    {% endfor %}
                </div>
            </td>
            {% endfor %}
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}